; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = 
	adafruit/Adafruit_VL53L0X@^1.2.5
<<<<<<< HEAD
	pololu/VL53L0X@^1.3.1
monitor_speed = 115200
=======
	pololu/VL53L0X@^1.3.1
>>>>>>> 86fb7754b15c5a5fe14103e986d295378b0f789f
